[project]
name = "team-project"
version = "0.1.0"
description = "simple team project"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "black>=25.1.0",
    "pyside6==6.9.0",
    "pyside6-verticalqtabwidget>=0.0.3",
]
